export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SAVE_PROFILE_SUCCESS = 'SAVE_PROFILE_SUCCESS';
export const SAVE_PROFILE_FAIL = 'SAVE_PROFILE_FAIL';
export const USER_VERIFIED = 'USER_VERIFIED';