export const GET_STORE_DETAILS = 'GET_STORE_DETAILS';
export const UPDATE_STORE_DETAILS = 'UPDATE_STORE_DETAILS';
export const ADD_STORE_DETAILS_SUCCESS = 'ADD_STORE_DETAILS_SUCCESS';
export const ADD_STORE_DETAILS_FAIL = 'ADD_STORE_DETAILS_FAIL';

